"""Idempotently ensures AndroidManifest.xml declares the permissions this
app needs (camera, location, internet). Safe to run every CI build,
whether android/ was just freshly generated by `flutter create` or was
already committed to the repo with these permissions in place.
"""
import sys

MANIFEST_PATH = "android/app/src/main/AndroidManifest.xml"

REQUIRED_PERMISSIONS = [
    "android.permission.CAMERA",
    "android.permission.ACCESS_FINE_LOCATION",
    "android.permission.ACCESS_COARSE_LOCATION",
    "android.permission.INTERNET",
]


def main() -> int:
    try:
        with open(MANIFEST_PATH, encoding="utf-8") as f:
            content = f.read()
    except FileNotFoundError:
        print(f"ERROR: {MANIFEST_PATH} not found.", file=sys.stderr)
        return 1

    missing = [p for p in REQUIRED_PERMISSIONS if p not in content]

    if not missing:
        print("All required permissions already present — nothing to do.")
        return 0

    manifest_tag_start = content.index("<manifest")
    insertion_point = content.index(">", manifest_tag_start) + 1
    injected = "\n".join(f'    <uses-permission android:name="{p}"/>' for p in missing)
    content = content[:insertion_point] + "\n" + injected + content[insertion_point:]

    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        f.write(content)

    print("Added permissions:", ", ".join(missing))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
